### ISSUE TITLE
Modify 07-tendermint client specifications in order to also support TAO v2 spec.

### ISSUE THREAD

**Issue by AdityaSripal** [cosmos/ibc#1135]
- Deprecate delay period parameters in the verification methods
- Add new parameters into the ClientState itself to use in verification method

I don't think we need to create a new spec, but it should be clear how the delay period parameters are being moved into the client for v2 and will no longer be passed in.

**Comment by sangier** [comment]
Closed by https://github.com/cosmos/ibc/pull/1137
