### ISSUE TITLE
ICS4: v2 handling of packet flow

### ISSUE THREAD

**Issue by AdityaSripal** [cosmos/ibc#1140]
In v2, the only functions that are necessary for 04-channel are the packet flow handlers. Should we rename this spec so it is no longer called channel?

- Retain only the packet flow handlers and ensure all similar checks are still made
- Specify and explain new packet structure (including multidata)
- Specify and explain new acknowledgment structure (including metadata)
- Specify and explain how the packet flow handler will route verification to the underlying client and route application data to all relevant applications

**Comment by sangier** [comment]
Closed by https://github.com/cosmos/ibc/pull/1148
