### ISSUE TITLE
ICS20: Support v2 TAO in ICS20 spec

### ISSUE THREAD

**Issue by AdityaSripal** [cosmos/ibc#1141]
Make changes to support v2 TAO for ICS20. We need to figure out how to clearly communicate this, as there is ICS20v1 and ICS20 v2. While both versions of ICS20 can be modified to support v2 TAO. Thus we need to find a way to clearly communicate this version compatibility matrix

**Comment by sangier** [comment]
Closed by https://github.com/cosmos/ibc/pull/1157
