### ISSUE TITLE
I am trying to set up and test IBC communication between two chains on my local environment

### ISSUE THREAD

**Issue by dhiraj-mishra-it** [cosmos/ibc#1169]
### Question
I am trying to set up and test IBC communication between two chains on my local environment but facing issues with the configuration and relayer setup.

### Steps I Have Taken
1. Set up two Cosmos SDK-based chains (`chainA` and `chainB`) locally.
2. Initialized and started both chains successfully using `gaiad` commands.
3. Installed and configured the relayer (`rly`) with the following steps:
   - Created configurations for both chains in the `config.yaml`.
   - Linked the two chains using `rly tx link`.
4. Attempted to send a packet using `rly tx xfer` between the chains.

### Problem
The `rly config init` command fails with the following error:
Command 'rly' not found, did you mean:
  command 'rls' from snap rustup (1.27.1)
  command 'ly' from deb python3-ly (0.9.6-2)
See 'snap info <snapname>' for additional versions.

**Comment by womensrights** [comment]
Hello there, please direct support requests to the [interchain discord server](https://discord.gg/interchain) where someone will be on hand to help you out, this also seems to be an issue with [the relayer](https://github.com/cosmos/relayer)
