### ISSUE TITLE
Question: Clarification on support for optimistic packet sending in ICS-004

### ISSUE THREAD

**Issue by bluele** [cosmos/ibc#1170]
Hi there,

In the current IBC specifications, is the lack of support for optimistic packet sending intentional?

As described [here](https://github.com/cosmos/ibc/blob/47fea20d4d400e967721396092c6b43398c65d78/spec/core/ics-004-channel-and-packet-semantics/README.md?plain=1#L764), the channel state is required to be OPEN when sending a packet.
Additionally, I know that the ibc-go has decided to remove support for optimistic packet sending in [this issue](https://github.com/cosmos/ibc-go/issues/2670).

However, if optimistic packet sending is not supported in the ICS-004 as well, [the following description about packet timeout](https://github.com/cosmos/ibc/blob/47fea20d4d400e967721396092c6b43398c65d78/spec/core/ics-004-channel-and-packet-semantics/README.md?plain=1#L1157) in the document seems misleading or incorrect:
> Since we allow optimistic sending of packets (i.e. sending a packet before a channel opens), we must also allow optimistic timing out of packets. With optimistic sends, the packet may be sent on a channel that eventually opens or a channel that will never open. If the channel does open after the packet has timed out, then the packet will never be received on the counterparty so we can safely timeout optimistically. If the channel never opens, then we MUST timeout optimistically so that any state changes made during the optimistic send by the application can be safely reverted.

Could you clarify whether this feature is supported and whether the current description aligns with the intended design?

**Comment by AdityaSripal** [comment]
Hello, we disabled optimistic sends and so yes the description in packet timeout is outdated and inaccurate. Thank you for the catch!

Would you like to make a PR fixing this?

**Comment by bluele** [comment]
@AdityaSripal  Thank you for confirming!
I'd be happy to create a PR to fix this. I’ll work on it shortly.
