### ISSUE TITLE
ICS28: Move CCV V1 spec from Draft to Candidate

### ISSUE THREAD

**Issue by mpoke** [cosmos/ibc#671]
Move the specification of Cross-Chain Validation V1 to Candidate stage. This requires the following tasks to be completed:

- [x] Merge https://github.com/cosmos/ibc/pull/666
- [ ] Check that the [go implementation](https://github.com/cosmos/interchain-security) follows the specification.

**Comment by crodriguezvega** [comment]
@mpoke Now that ICS28 is in production with a Go implementation, can we mark the spec as candidate?
