### ISSUE TITLE
ICS028: VSC is not sent in particular case, but it should be

### ISSUE THREAD

**Issue by danwt** [cosmos/ibc#742]
Consider the following sequence

A) a BONDED validator v0 loses power, falling to p0 and becoming UNBONDING
B) a BONDED validator v1 loses power, falling to p1 < p0 and becoming UNBONDING. v0 is now BONDED
   

I think that according to the spec

https://github.com/cosmos/ibc/blob/a6bc8d14dc1fc45cdcd052e6da8c6765389b7d61/spec/app/ics-028-cross-chain-validation/technical_specification.md?plain=1#L70-L75

the updates ultimately come from `SetValidatorUpdate` calls in the sdk. These are only made in two places

1. If power _changes_ for a validator

https://github.com/cosmos/cosmos-sdk/blob/e75e83fa99fc9ce8ffdf6717f780cd1c78b06ad4/x/staking/keeper/val_state_change.go#L182-L189

2. If a validator becomes no longer bonded

https://github.com/cosmos/cosmos-sdk/blob/e75e83fa99fc9ce8ffdf6717f780cd1c78b06ad4/x/staking/keeper/val_state_change.go#L202-L221

Notice that neither of these cases occur in Block B) described above for validator v0. Therefore there will not be an update sent from provider to consumer regarding v0, and the consumer will _continue to think that v0 is not validating_.

**Comment by danwt** [comment]
There's a good chance I've made a mistake in my understanding here, if so, please feel free to close the issue :)

**Comment by mpoke** [comment]
> Notice that neither of these cases occur in Block B) described above for validator v0. 

@danwt I'm not sure that I follow. Are the events in A) and B) happening in the same block or in different blocks?  

Keep in mind that the code at 1. and 2. is executed at the end of the block; by that time, the powers of the validators was already updated and it's not going to change during the execution of ` ApplyAndReturnValidatorSetUpdates`.  

> A) a BONDED validator v0 loses power, falling to p0 and becoming UNBONDING

This means that v0 is no longer in the first `maxValidators` validators (cf. https://github.com/cosmos/cosmos-sdk/blob/e75e83fa99fc9ce8ffdf6717f780cd1c78b06ad4/x/staking/keeper/val_state_change.go#L132)

> B) a BONDED validator v1 loses power, falling to p1 < p0 and becoming UNBONDING. v0 is now BONDED

This means that v0 is again in the first `maxValidators` validators, and it will be added to the validator set via the code in 1.

**Comment by danwt** [comment]
Hey you are right I misread something :)
