### ISSUE TITLE
ICS28: system aborted due to update aggregation logic

### ISSUE THREAD

**Issue by danwt** [cosmos/ibc#743]
## Context

In the consumer EndBlock the received updates are aggregated and then processed

https://github.com/cosmos/ibc/blob/a6bc8d14dc1fc45cdcd052e6da8c6765389b7d61/spec/app/ics-028-cross-chain-validation/technical_specification.md?plain=1#L1734-L1743

the aggregation is defined

https://github.com/cosmos/ibc/blob/a6bc8d14dc1fc45cdcd052e6da8c6765389b7d61/spec/app/ics-028-cross-chain-validation/technical_specification.md?plain=1#L348-L351

and the aggregated updates are processed:

https://github.com/cosmos/ibc/blob/a6bc8d14dc1fc45cdcd052e6da8c6765389b7d61/spec/app/ics-028-cross-chain-validation/technical_specification.md?plain=1#L1775-L1781

## Scenario

If a validator v0 receives a power=0 update on the consumer in block A then the validator will be deleted

https://github.com/cosmos/ibc/blob/a6bc8d14dc1fc45cdcd052e6da8c6765389b7d61/spec/app/ics-028-cross-chain-validation/technical_specification.md?plain=1#L1791-L1793

but if subsequently the the pendingUpdates struct fills up with, e.g.

```
[(v0, 42), (v0, 0)]
```

then the aggregation will reduce this to 

```
[ (v0, 0)]
```

which will trigger this branch

https://github.com/cosmos/ibc/blob/a6bc8d14dc1fc45cdcd052e6da8c6765389b7d61/spec/app/ics-028-cross-chain-validation/technical_specification.md?plain=1#L1779-L1781

causing a panic

**Comment by mpoke** [comment]
@danwt That's true. Nice catch. Could you please open an issue on the implementation side also?
