### ISSUE TITLE
ICS28: doubts about property `Bond-Based Consumer Voting Power` when double sign slashing

### ISSUE THREAD

**Issue by danwt** [cosmos/ibc#772]
I think the property `Bond-Based Consumer Voting Power`

https://github.com/cosmos/ibc/blob/5be51c0639ddb9960607df487dfb25e727dea2fa/spec/app/ics-028-cross-chain-validation/system_model_and_properties.md?plain=1#L115-L129

is not precise enough w.r.t the definition `pBonded(h,val)`

https://github.com/cosmos/ibc/blob/5be51c0639ddb9960607df487dfb25e727dea2fa/spec/app/ics-028-cross-chain-validation/system_model_and_properties.md?plain=1#L97-L98

especially in the wording `includes also unbonding tokens (i.e., tokens in the process of being unbonded);`

This is because there are multiple ways tokens 'can be unbonding' or similar

1. The validator is bonded or in the unbonding queue and has slashable tokens
2. There are unbonding delegations associated to the validator
  - each unbonding delegation has an `initialBalance`. This is not slashable.
  - each unbonding delegation has a `balance`. This is initially equal to initialBalance and is slashable. This is what is refunded on expiry.

I'm wondering what happens when a validator is slashed and this code is triggered

https://github.com/cosmos/cosmos-sdk/blob/208585015838b420d2f7712c1a5c16e0bd2a5b3b/x/staking/keeper/slash.go#L122-L124

I'm not sure how we can relate this case to `Bond-Based Consumer Voting Power`. IMO part of the difficulty is that we are trying to be very precise and write a spec that builds on top of staking and slashing, which are not really specced.

**Comment by danwt** [comment]
Hi @mpoke, any thoughts on this?

**Comment by mpoke** [comment]
@danwt The idea of this property is that a validator cannot unlock the tokens that gave it the power to validate on the consumer chain before the unbonding period elapses since the last time that power was used. I agree that the definition of `pBonded(h,val)` does not contain anything about the amount of tokens slashed.
