### ISSUE TITLE
ICS 004: SendPacket interface should return the packet sequence

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc#819]
SendPacket now gets the next send sequence and includes it in the packet as the packet sequence. Applications calling this function will not know which sequence belongs to a `SendPacket` call unless the sequence is returned. Thus, I recommend that the packet sequence be returned in a `SendPacket` call. This is analogous to sending a package and receiving a tracking number

**Comment by crodriguezvega** [comment]
I believe when [this PR is merged](https://github.com/cosmos/ibc-go/pull/1703) ibc-go will have implemented this, so it will be ahead of the spec.
