### ISSUE TITLE
ICS28: Reflect that unbonding maturations occur after Staking.EndBlock in spec

### ISSUE THREAD

**Issue by danwt** [cosmos/ibc#825]
Mirror issue

- https://github.com/cosmos/interchain-security/issues/299#issuecomment-1227411907

Long story short, in the code unbonding maturations complete after Staking.EndBlock but in the spec they happen before.

**Comment by mpoke** [comment]
@danwt I think this issue is a duplicate of https://github.com/cosmos/ibc/issues/781, right?

**Comment by danwt** [comment]
It's more or less a duplicate yes, I've closed the other one now. I had written something a bit misleading there anyway.
