### ISSUE TITLE
ICS7: Tendermint client trustLevel `=1` should be considered valid

### ISSUE THREAD

**Issue by hu55a1n1** [cosmos/ibc#857]
[Client initialization for the Tendermint](https://github.com/cosmos/ibc/blob/main/spec/client/ics-007-tendermint-client/README.md#client-initialisation) light client treats `1` as an invalid value -> 
```
function initialise(/* ... */): ClientState {
    // ...
    assert(trustLevel > 0 && trustLevel < 1)
```

But, tendermint-go allows it -> https://github.com/tendermint/tendermint/blob/b42c439776811a6fcab8e22fb97fb44cee5701b3/light/verifier.go#L194-L204

**Comment by crodriguezvega** [comment]
Thanks, @hu55a1n1. I guess we should also update the [minimum allowed value to 1/3](https://github.com/tendermint/tendermint/blob/b42c439776811a6fcab8e22fb97fb44cee5701b3/light/verifier.go#L201) instead of 0?

**Comment by hu55a1n1** [comment]
> I guess we should also update the [minimum allowed value to be >= 1/3](https://github.com/tendermint/tendermint/blob/b42c439776811a6fcab8e22fb97fb44cee5701b3/light/verifier.go#L201) instead of just > 0?

Good point, I missed that! :+1: The allowed range should be `[1/3, 1]`.
