### ISSUE TITLE
ICS28: Slash packet throttling

### ISSUE THREAD

**Issue by mpoke** [cosmos/ibc#896]
This feature would make it impossible to jail more than `x%` (probably between 1-5%) of the power on the provider per hour. As a result, an attacker that compromises a consumer chain cannot slash and jail all the provider active validators at once and replace them with its own validator set.

See https://github.com/cosmos/interchain-security/issues/404 and https://github.com/cosmos/interchain-security/pull/462 for more details.

**Comment by smarshall-spitzbart** [comment]
@mpoke looks like we won't have to start from complete scratch when writing the spec for throttling, they've already formulated some of the math. See https://github.com/cosmos/interchain-security/issues/685#issuecomment-1409028720

**Comment by smarshall-spitzbart** [comment]
See also https://github.com/cosmos/interchain-security/pull/682

**Comment by mpoke** [comment]
The jail throttling (aka slash throttling) is meant as a temporary solution for dealing with [untrusted consumer chains](https://github.com/cosmos/ibc/issues/923), i.e., both *Safe Blockchain* and *Live Blockchain* assumptions are dropped for the consumers. Thus, it is sufficient to have this feature described in an ADR on the implementation side.
